# Generated by Django 5.2.4 on 2025-08-03 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('position_type', models.CharField(choices=[('intern', 'Intern'), ('volunteer', 'Volunteer')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_education', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('relevant_experience', models.TextField()),
                ('motivation', models.TextField()),
                ('skills', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
